version: '2.1'
services:
    rabbitmq:
       image: rabbitmq:3-management
       ports:
         - 15672:15672
         - 5672:5672
       container_name: rabbitmq
       environment:
         - RABBITMQ_HOST=rabbitmq
         - RABBITMQ_USER=guest
         - RABBITMQ_PASS=guest
         - RABBITMQ_DEFAULT_VHOST=/
         - HEALTH_CHECK_CACHE=0
    bancp-mysql:
        image: mysql:8.0
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=bancobeerdb
          - MYSQL_USER=admin
          - MYSQL_PASSWORD=admin
        ports:
          - 3307:3307 
         
    
